server:
  port: 5050

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/elearningdb
    username: root
    password: root
